apiVersion: v1
kind: Service
metadata:
  labels:
    app: ecom-web-service
  name: ecom-web-service
spec:
  selector:
    app: ecom-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
